#!/usr/bin/env -S deno run -A --watch=static/,routes/

import dev from "$fresh/dev.ts";
import { watchMdx } from "https://deno.land/x/watch_mdx@v0.0.7/mod.ts";

const precompile =
  Deno.args.findLast((arg) => arg === "--precompile") !== undefined;

// deno-lint-ignore no-explicit-any
const lock = precompile && (function (this: any) {
  this.release = new Promise((resolve) => {
    this.resolve = resolve;
  });
  return this;
}.bind({}))();

watchMdx({
  precompile,
  compile: async ({ compile, source, output }) => {
    const result = await compile(source.value, {
      providerImportSource: null,
      jsxImportSource: "preact",
      jsx: true,
    });
    const value = `
    // DO NOT EDIT. This file is generated by \`watch_mdx\`.
    // This file SHOULD be checked into source version control.
    // This file is automatically updated during development when running \`dev.ts\`.

    ${result.value}
    `;
    return {
      value,
      output,
    };
  },
  onCompile: lock ? lock.resolve : undefined,
});

if (precompile) {
  await lock.release;
  Deno.exit(0);
}

await dev(import.meta.url, "./main.ts");
