// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/components.jsx";
import * as $5 from "./routes/index.tsx";
import * as $$0 from "./islands/HelixAnimation.tsx";
import * as $$1 from "./islands/HexoCube.tsx";
import * as $$2 from "./islands/LangSwitcher.tsx";
import * as $$3 from "./islands/LazyHexoCube.tsx";
import * as $$4 from "./islands/MenuButton.tsx";
import * as $$5 from "./islands/MenuLink.tsx";
import * as $$6 from "./islands/PopoverShowcase.tsx";
import * as $$7 from "./islands/StackIcons.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/api/joke.ts": $3,
    "./routes/components.jsx": $4,
    "./routes/index.tsx": $5,
  },
  islands: {
    "./islands/HelixAnimation.tsx": $$0,
    "./islands/HexoCube.tsx": $$1,
    "./islands/LangSwitcher.tsx": $$2,
    "./islands/LazyHexoCube.tsx": $$3,
    "./islands/MenuButton.tsx": $$4,
    "./islands/MenuLink.tsx": $$5,
    "./islands/PopoverShowcase.tsx": $$6,
    "./islands/StackIcons.tsx": $$7,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
